package it.alessandrochillemi.tesi.WLGenerator;

//Possibili classi di equivalenza per ogni parametro
public enum EquivalenceClass {
	STR_NULL,STR_EMPTY,STR_VERY_LONG,STR_INVALID,STR_VALID,
	COL_NULL,COL_EMPTY,COL_VERY_LONG,COL_INVALID,COL_VALID,
	DATE_NULL,DATE_EMPTY,DATE_VERY_LONG,DATE_INVALID,DATE_VALID,
	NUM_NULL,NUM_EMPTY,NUM_ABSOLUTE_MINUS_ONE,NUM_ABSOLUTE_ZERO,NUM_VERY_BIG,NUM_VALID,
	LIST_NULL,LIST_EMPTY,LIST_VALID,
	BOOLEAN_NULL,BOOLEAN_EMPTY,BOOLEAN_VALID
}
